replicaCount: 2

image:
  repository: 892387177992.dkr.ecr.ap-south-1.amazonaws.com/tetris
  tag: 86
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30105

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
